version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - unconvert
    - unparam
    - gosec

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes:
      - datactl
  misspell:
    locale: US

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
